Feat profile api
SkyPedal/skypedal-backend pull request #12
Opened 2024-08-13 15:04 UTC by sammyswe

backend for profile page complete including tests.

2024-08-14 09:16 UTC, WilliamMoolman requested changes
Looks really solid. Due to Vlad's security PR, there will be a few merge conflicts as he's had to make certain changes to the User class for spring security to be happy. Once he's merged, maybe you and he could go through the merge conflict together?

2024-08-14 09:16 UTC, WilliamMoolman commented on src/main/resources/application.properties
> +spring.sql.init.data-locations=classpath:data.sql
Currently application.properties is set up alongisde application-[dev/prod/test].properties, so we shouldn't need to add anything to it. Data-locations defaults to data.sql so that should be good, but we currently want schema locations to point to schema.sql. Could you remove these lines, and move the schema data from users.sql to schema.sql?

2024-08-14 09:16 UTC, WilliamMoolman commented on src/test/java/com/skypedal/skypedal_backend/rest/UserControllerIntegrationTest.java
> +@AutoConfigureMockMvc
When merging in after vlad's pull request, you'll need to change this line to `@AutoConfigureMockMVC(addFilter = false)` to not conflict

2024-08-14 09:16 UTC, WilliamMoolman commented on src/test/java/com/skypedal/skypedal_backend/rest/UserControllerIntegrationTest.java
> +@Sql(scripts = {"classpath:test/users.sql", "classpath:test/data.sql"},
Here we are also using `@Sql(scripts = {"classpath:/test/test-schema.sql", "classpath:test/test-data.sql"}, executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD)` so that we can have a single schema and data for testing. Could you move rename these files?

2024-08-14 10:17 UTC, WilliamMoolman commented on src/main/java/com/skypedal/skypedal_backend/Exceptions/UserNotFoundException.java
> +package com.skypedal.skypedal_backend.Exceptions;
Could you move this file to lowercase package `exceptions`?

2024-08-14 10:17 UTC, WilliamMoolman commented on src/main/java/com/skypedal/skypedal_backend/Services/UserService.java
> +package com.skypedal.skypedal_backend.Services;
Same with this once, to `services` instead of `Services`

2024-08-14 14:35 UTC, sammyswe reviewed
done

2024-08-14 15:31 UTC, WilliamMoolman requested changes
Currently test-data.sql and test-schema.sql are in src/tests/resources/test, however we are currently putting them in src/main/resources/test. Could you copy over the contents to those files? Currently other tests are failing

2024-08-14 16:14 UTC, WilliamMoolman approved these changes

2024-08-15 08:44 UTC, Neutralas approved these changes
keep up the good work!

2024-08-15 08:47 UTC, merged